### PR TITLE
variant version of shopify viewed product

### PR DESCRIPTION
**Pull request by wbendris-klaviyo**
adds a snippet that can replace our default Viewed Product for Shopify, sync variant info as well, and run on page load and variant change (also retain original code's data and structure)

### CODE REVIEW

**Comment by cbarley10** [comment]
nit - and i probably have to clean up some more stuff, but can you change the file and folder names to dashes just to keep some kind of convention?

**Comment by wbendris-klaviyo** [comment]
> nit - and i probably have to clean up some more stuff, but can you change the file and folder names to dashes just to keep some kind of convention?

sure! the folder name is but i assumed we were keeping filenames to the convention of the language they were in (eg. camel case for JS, snake case for python). If filenames are also the dash convention, i'll do that from now on

**Comment by cbarley10** [comment]
Hm yeah what do you think? im down for any convention

**Comment by wbendris-klaviyo** [comment]
I think naming the files per-language looks nicer and more plug-and-play if you're familiar with the language, but dash notation looks cleaner and more cohesive if it's used across every file, like we're managing a coding assistance tool rather than hosting a bucket of code. I'll swap it to the dash notation

**Comment by cbarley10** [comment]
sounds good! everything looks good to me. merging

**Pull request merged**
